#!/bin/sh

##########################################################
###### Treegix agent daemon init script
##########################################################

case $1 in

start)
	/usr/local/sbin/treegix_agentd -c /usr/local/etc/treegix_agentd.conf ;;

stop)
	kill -TERM `cat /tmp/treegix_agentd.pid` ;;

restart)
	$0 stop
	sleep 10
	$0 start
	;;

*)
	echo "Usage: $0 start|stop|restart"
	exit 1
esac
