postgres:
  image: postgres
  ports:
    - 5432:5432
  volumes:
    - ./database/postgresql/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
    - ./database/postgresql/data.sql:/docker-entrypoint-initdb.d/2-data.sql
    - ./database/postgresql/images.sql:/docker-entrypoint-initdb.d/3-images.sql
    - ./data/pg:/var/lib/postgresql/data

treegix_server:
  image: treegix_server:latest
  ports:
    - 10051:10051

frontend:
  image: treegix_web:latest
  ports:
    - 81:80

