#!/bin/bash

# Source function library.

. /etc/init.d/functions

RETVAL=0
prog="Treegix Server"
TREEGIX_BIN="/usr/local/sbin/treegix_server"

if [ ! -x ${TREEGIX_BIN} ] ; then
        echo -n "${TREEGIX_BIN} not installed! "
        # Tell the user this has skipped
        exit 5
fi

start() {
        echo -n $"Starting $prog: "
        daemon $TREEGIX_BIN
        RETVAL=$?
        [ $RETVAL -eq 0 ] && touch /var/lock/subsys/treegix_server
        echo
}

stop() {
        echo -n $"Stopping $prog: "
        killproc $TREEGIX_BIN
        RETVAL=$?
        [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/treegix_server
        echo
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  reload|restart)
        stop
        sleep 10
        start
        RETVAL=$?
        ;;
  condrestart)
        if [ -f /var/lock/subsys/treegix_server ]; then
            stop
            start
        fi
        ;;
  status)
        status $TREEGIX_BIN
        RETVAL=$?
        ;;
  *)
        echo $"Usage: $0 {condrestart|start|stop|restart|reload|status}"
        exit 1
esac

exit $RETVAL
