#!/bin/bash
#
#       /etc/rc.d/init.d/treegix_agentd
#
# Starts the treegix_agentd daemon
#
# chkconfig: - 95 5
# description: Treegix Monitoring Agent
# processname: treegix_agentd
# pidfile: /tmp/treegix_agentd.pid

# Modified for Treegix 2.0.0
# May 2012, Treegix SIA

# Source function library.

. /etc/init.d/functions

RETVAL=0
prog="Treegix Agent"
ZABBIX_BIN="/usr/local/sbin/treegix_agentd"

if [ ! -x ${ZABBIX_BIN} ] ; then
        echo -n "${ZABBIX_BIN} not installed! "
        # Tell the user this has skipped
        exit 5
fi

start() {
        echo -n $"Starting $prog: "
        daemon $ZABBIX_BIN
        RETVAL=$?
        [ $RETVAL -eq 0 ] && touch /var/lock/subsys/treegix_agentd
        echo
}

stop() {
        echo -n $"Stopping $prog: "
        killproc $ZABBIX_BIN
        RETVAL=$?
        [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/treegix_agentd
        echo
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  reload|restart)
        stop
        sleep 10
        start
        RETVAL=$?
        ;;
  condrestart)
        if [ -f /var/lock/subsys/treegix_agentd ]; then
            stop
            start
        fi
        ;;
  status)
        status $ZABBIX_BIN
        RETVAL=$?
        ;;
  *)
        echo $"Usage: $0 {condrestart|start|stop|restart|reload|status}"
        exit 1
esac

exit $RETVAL
