#! /bin/sh
# Copyright (c) 07/2004 A.Tophofen, Germany
# Modified for Treegix 1.1alpha7 and SuSE Linux 9.2
# April 2005, A. Kiepe, Switzerland
# Modified for Treegix 2.0.0
# May 2012, Treegix SIA
#
# init.d/treegix_server
#
### BEGIN INIT INFO
# Provides:       treegix_server
# Required-Start: $network $remote_fs $syslog 
# Should-Start:   mysql postgresql
# Required-Stop:
# Default-Start:  3 
# Default-Stop:
# Description:    Starts treegix_server
### END INIT INFO

. /etc/rc.status
rc_reset
NAME="treegix_server"

ZABBIX_BIN="/usr/local/sbin/treegix_server"
ZABBIX_PID="/tmp/treegix_server.pid"

if [ ! -x ${ZABBIX_BIN} ] ; then
	echo -n "${ZABBIX_BIN} not installed! "
	# Tell the user this has skipped
	rc_status -s
	exit 5
fi

export PATH=$PATH:/usr/local/sbin

case "$1" in
    start)
	echo -n "Starting ${NAME} "
	checkproc -p ${ZABBIX_PID} ${ZABBIX_BIN}
	case $? in
		0) echo -n "- Warning: ${NAME} already running! " ;;
		1) echo -n "- Warning: ${ZABBIX_PID} exists! " ;;
	esac
	
	startproc -p ${ZABBIX_PID} -u treegix ${ZABBIX_BIN}
	rc_status -v
	;;
    stop)
	echo -n "Shutting down ${NAME}"
	checkproc -p ${ZABBIX_PID} ${ZABBIX_BIN} || echo -n "- Warning: ${NAME} not running! "
	killproc -p ${ZABBIX_PID} -TERM ${ZABBIX_BIN}
	rc_status -v
	;;
    restart)
	$0 stop
	sleep 10
	$0 start
	rc_status
	;;
        *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
	;;
esac
rc_exit

