#! /bin/sh
#
# init.d/treegix_agentd
#
### BEGIN INIT INFO
# Provides:       treegix_agentd
# Required-Start: $network $remote_fs $syslog
# Required-Stop:
# Default-Start:  3 
# Default-Stop:
# Description:    Starts Treegix_Agentd
### END INIT INFO

. /etc/rc.status
rc_reset
NAME="Treegix_Agentd"

TREEGIX_BIN="/usr/local/sbin/treegix_agentd"
TREEGIX_PID="/tmp/treegix_agentd.pid"

if [ ! -x ${TREEGIX_BIN} ] ; then
	echo -n "${TREEGIX_BIN} not installed! "
	# Tell the user this has skipped
	rc_status -s
	exit 5
fi

export PATH="/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/sbin"

case "$1" in
    start)
	echo -n "Starting ${NAME} "
	checkproc -p ${TREEGIX_PID} ${TREEGIX_BIN}
	case $? in
		0) echo -n "- Warning: ${NAME} already running! " ;;
		1) echo -n "- Warning: ${TREEGIX_PID} exists! " ;;
	esac
	
	startproc -p ${TREEGIX_PID} ${TREEGIX_BIN} -u treegix
	rc_status -v
	;;
    stop)
	echo -n "Shutting down ${NAME}"
	checkproc -p ${TREEGIX_PID} ${TREEGIX_BIN} || echo -n "- Warning: ${NAME} not running! "
	killproc -p ${TREEGIX_PID} -TERM ${TREEGIX_BIN}
	rc_status -v
	;;
    restart)
	$0 stop
	sleep 10
	$0 start
	rc_status
	;;
        *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
	;;
esac
rc_exit

