

#ifndef TREEGIX_SYSINFO_COMMON_CPU_H
#define TREEGIX_SYSINFO_COMMON_CPU_H

#include "sysinfo.h"

int	SYSTEM_CPU_DISCOVERY(AGENT_REQUEST *request, AGENT_RESULT *result);

#endif	/* TREEGIX_SYSINFO_COMMON_CPU_H */
