

#ifndef TREEGIX_SYSINFO_COMMON_HTTP_H
#define TREEGIX_SYSINFO_COMMON_HTTP_H

#include "sysinfo.h"

extern char	*CONFIG_SOURCE_IP;

int	WEB_PAGE_GET(AGENT_REQUEST *request, AGENT_RESULT *result);
int	WEB_PAGE_PERF(AGENT_REQUEST *request, AGENT_RESULT *result);
int	WEB_PAGE_REGEXP(AGENT_REQUEST *request, AGENT_RESULT *result);

#endif /* TREEGIX_SYSINFO_COMMON_HTTP_H */
