

#ifndef TREEGIX_SYSINFO_COMMON_SYSTEM_H
#define TREEGIX_SYSINFO_COMMON_SYSTEM_H

#include "sysinfo.h"

int	SYSTEM_LOCALTIME(AGENT_REQUEST *request, AGENT_RESULT *result);
int	SYSTEM_USERS_NUM(AGENT_REQUEST *request, AGENT_RESULT *result);

#endif /* TREEGIX_SYSINFO_COMMON_SYSTEM_H */
