
#ifndef TREEGIX_VERSION_H
#define TREEGIX_VERSION_H

#define TRX_STR2(str)	#str
#define TRX_STR(str)	TRX_STR2(str)

#define APPLICATION_NAME	"Treegix Agent"
#define TREEGIX_REVDATE		"28 October 2019"
#define TREEGIX_VERSION_MAJOR	4
#define TREEGIX_VERSION_MINOR	4
#define TREEGIX_VERSION_PATCH	1
#define TREEGIX_VERSION_REVISION	8870606e6a
#ifdef _WINDOWS
#	define TREEGIX_VERSION_RC_NUM	1400
#endif
#define TREEGIX_VERSION_RC	""
#define TREEGIX_VERSION		TRX_STR(TREEGIX_VERSION_MAJOR) "." TRX_STR(TREEGIX_VERSION_MINOR) "." \
				TRX_STR(TREEGIX_VERSION_PATCH) TREEGIX_VERSION_RC
#define TREEGIX_REVISION		TRX_STR(TREEGIX_VERSION_REVISION)

int	zbx_get_component_version(char *value);

#endif
